# Generated by Django 4.1.6 on 2023-02-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, max_length=60)),
                ('text', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='imageName',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='Tags_Post', to='blog.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
